# Generated by Django 5.0.6 on 2024-05-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
    ]
