# Generated by Django 5.0.6 on 2024-05-21 02:39

import agenda.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_cita_paciente'),
        ('main', '0009_recepcionista_correo_recepcionista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(validators=[agenda.models.validar_dia]),
        ),
        migrations.CreateModel(
            name='HorarioVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio_manana', models.TimeField(default=datetime.time(9, 0))),
                ('hora_fin_manana', models.TimeField(default=datetime.time(13, 0))),
                ('hora_inicio_tarde', models.TimeField(default=datetime.time(15, 0))),
                ('hora_fin_tarde', models.TimeField(default=datetime.time(18, 0))),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.veterinario')),
            ],
        ),
    ]
