# Generated by Django 5.0.6 on 2024-05-21 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_cita_fecha_cita_horarioveterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioveterinario',
            name='hora_fin_manana',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='horarioveterinario',
            name='hora_inicio_tarde',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
    ]
