# Generated by Django 5.0.6 on 2024-05-23 17:51

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_horarioveterinario_hora_fin_manana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.CharField(choices=[('1', '09:00 hasta 10:00'), ('2', '10:00 hasta 11:00'), ('3', '11:00 hasta 12:00'), ('4', '12:00 hasta 13:00'), ('5', '13:00 hasta 14:00'), ('6', '14:00 hasta 15:00'), ('7', '15:00 hasta 16:00'), ('8', '16:00 hasta 17:00'), ('9', '17:00 hasta 18:00'), ('10', '18:00 hasta 19:00'), ('11', '19:00 hasta 20:00')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(help_text='Ingrese un fecha para la agenda', validators=[agenda.models.validar_dia]),
        ),
    ]
