# Generated by Django 5.0.6 on 2024-05-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cita_horario_alter_cita_fecha_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='hora_cita',
        ),
    ]
