# Generated by Django 5.0.6 on 2024-06-17 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_cita_hora_cita'),
        ('main', '0011_alter_veterinario_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('horario', 'fecha_cita', 'veterinario', 'sucursal'), name='unique_cita'),
        ),
    ]
