# Generated by Django 5.0.6 on 2024-06-26 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0013_delete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('sexo_paciente', models.BooleanField(choices=[(True, 'Masculino'), (False, 'Femenino')])),
                ('fecha_nacimiento_paciente', models.DateField()),
                ('color_paciente', models.CharField(max_length=25)),
                ('observacion_paciente', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='main.cliente')),
                ('tipo_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='main.tipopaciente')),
                ('tipo_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='main.tratamiento')),
            ],
        ),
    ]
