# Generated by Django 5.0.6 on 2024-05-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='provincia',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
