# Generated by Django 5.0.6 on 2024-05-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='descripcion_estado_civil',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo_paciente',
            field=models.BooleanField(choices=[(True, 'Masculino'), (False, 'Femenino')]),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_paciente',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='tipo_tratamiento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
