# Generated by Django 5.0.6 on 2024-05-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_estadocivil_descripcion_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='nombre_comuna',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='nombre_region',
        ),
        migrations.AddField(
            model_name='comuna',
            name='codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='comuna',
            name='codigo_padre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='comuna',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comuna',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='region',
            name='codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='region',
            name='codigo_padre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('url', models.URLField(blank=True)),
                ('codigo_padre', models.CharField(blank=True, max_length=10)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.provincia'),
        ),
    ]
