# Generated by Django 5.0.6 on 2024-05-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comuna_tipo_provincia_tipo_region_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='razapaciente',
            name='raza_ave',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='razapaciente',
            name='raza_gato',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='razapaciente',
            name='raza_perro',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_paciente',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
    ]
