# Generated by Django 5.0.6 on 2024-05-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_razapaciente_raza_ave_razapaciente_raza_gato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_ave',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_gato',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_perro',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
