# Generated by Django 5.0.6 on 2024-05-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_razapaciente_raza_ave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_ave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_gato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_paciente',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='razapaciente',
            name='raza_perro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
