# Generated by Django 5.0.6 on 2024-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_razapaciente_raza_ave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinario',
            name='dvrut_veterinario',
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='numrut_veterinario',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
