# Generated by Django 5.0.6 on 2024-05-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_veterinario_dvrut_veterinario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numrut_cliente',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
