# Generated by Django 5.0.6 on 2024-05-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cliente_comuna_alter_cliente_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionista',
            name='correo_recepcionista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='correo_veterinario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
