# Generated by Django 5.0.6 on 2024-05-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recepcionista_correo_recepcionista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sucursal'),
        ),
    ]
