# Generated by Django 5.0.6 on 2024-05-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_veterinario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sucursal'),
        ),
    ]
