# Generated by Django 5.0.6 on 2024-06-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cliente_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
